# Generated by Django 3.1.2 on 2021-10-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20211029_0814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
